### ISSUE TITLE
REPORTE DE PROYECTO DE VISUAL STUDIO

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-kem#1]
[REPORTE-VISUAL STUDIO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-kem/files/14313525/REPORTE-VISUAL.STUDIO.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by JORGELUIS2266** [comment]
ING. A nosotros usted nos iba a calificar

**Comment by josealfredo79** [comment]
Calificacion 19 Bien hecho y revisado...
